---
- name: Install required packages
  package:
    update_cache: yes
    name:
      - sshfs

- name: Upload SSH key
  copy:
    content: "{{ priv_key_b64 | b64decode }}"
    dest: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: 0600

# - name: enable user_allow_other in fuse config
#   lineinfile:
#     path: /etc/fuse.conf
#     regexp: '^#user_allow_other$'
#     line: 'user_allow_other'
#     state: present

# Do not show warnings about unknown SSH keys
- name: add ip_fileserver to know_hosts 
  shell: "ssh-keyscan {{ ip_fileserver }}>> ~/.ssh/known_hosts"


- name: Create dir for disk mount
  file:
    path: /data/{{ folder_name }}
    state: directory
    recurse: yes

- name: Adding fstab entry for gdelt remote mount point
  mount:
    path: /data/{{ folder_name }}
    src: "sshfs_user@{{ ip_fileserver }}:/data"
    fstype: fuse.sshfs
    opts: "defaults,_netdev,idmap=user,follow_symlinks,identityfile=/home/ubuntu/.ssh/id_rsa,allow_other,default_permissions"
    state: mounted


- name: Change permissions
  file:
    path: /data/{{ folder_name }}
    mode: 0755
    recurse: no
    state: directory






