- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars_files:
    - ./group_vars/vhp4-safety

  tasks:
    - name: I am confused
      command: 'whoami'
      register: myidentity

    - name: my secret identity
      debug:
        msg: '{{ myidentity.stdout }}'
   
    