- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: yes
  roles:
    - python3.7-ds

  vars_files:
    - ./group_vars/vscode

  tasks:
    # Install and configure jupyterhub
    - include: jupyterhub.yml

    # install code-server
    - name: Check if we have already downloaded this DEB file
      ansible.builtin.stat:
        path: "/var/cache/apt/archives/codeserver.deb"
      register: codeserver_debfile

    - name: "Download code-server"
      ansible.builtin.get_url: 
        url: https://github.com/coder/code-server/releases/download/v4.6.0/code-server_4.6.0_amd64.deb
        dest: "/var/cache/apt/archives/codeserver.deb"

    - name: "Install code-server"
      ansible.builtin.apt:
        deb: "/var/cache/apt/archives/codeserver.deb"
    # end code-server install

    - name: "Install VSCode code-server for proxying"
      ansible.builtin.pip:
        name: "jupyter-vscode-proxy"

