- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  become: yes
  roles:
    - python3.7-ds

  vars_files:
    - ./group_vars/vscode

  vars:
    # error when installing latest (node v18) on ubuntu 18, therefore node version 16 is installed
    NODEJS_VERSION: "16"

  tasks:
    # Node install needs to be moved to role
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present
    
    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present
    # End node install

    # install code-server
    - name: Check if we have already downloaded this DEB file
      ansible.builtin.stat:
        path: "/var/cache/apt/archives/codeserver.deb"
      register: codeserver_debfile

    - name: "Download code-server"
      ansible.builtin.get_url: 
        url: https://github.com/coder/code-server/releases/download/v4.6.0/code-server_4.6.0_amd64.deb
        dest: "/var/cache/apt/archives/codeserver.deb"

    - name: "Install code-server"
      ansible.builtin.apt:
        deb: "/var/cache/apt/archives/codeserver.deb"
    # end code-server install

    - name: "Install JupyterHub"
      ansible.builtin.pip:
        name: jupyterhub

    - name: "Install configurable-http-proxy"
      community.general.npm:
        name: "configurable-http-proxy"
        global: true

    - name: "Install jupyterlab notebook"
      ansible.builtin.pip:
        name: jupyterlab notebook
